apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/minikube-tutorial/pipeline:1ce2b2e6eb6c61fcbbdadd3af86c34e0d7ce28d5
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
